spring.application.name=news

spring.datasource.url=jdbc:mysql://localhost:3306/news_db?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.mvc.static-path-pattern=/**

app.storage.upload-dir=src/main/resources/static/uploads

cloudinary.cloud-name=du2ur4oya
cloudinary.api-key=921724925514527
cloudinary.api-secret=mjmG9DI6Q1MT8xQeFPVledv2xvQ
